[build-system]
requires = [
    "setuptools>=42",
    "scikit-build==0.14.1; platform_system=='Linux'",
    "scikit-build==0.15.0; platform_system!='Linux'",
    "Cython==3.0.0a11",
    "rapidfuzz_capi==1.0.5"
]
build-backend = "backend"
backend-path = ["_custom_build"]

[tool.isort]
profile = "black"
