[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "numpy==1.13.3; python_version=='2.7'",
    "oldest-supported-numpy; python_version>='3.5'"
]
build-backend = "setuptools.build_meta"