[build-system]
requires = [
    "setuptools>=42",
    "scikit-build @ git+https://github.com/scikit-build/scikit-build@master",
    "Cython==3.0.0a11",
    "rapidfuzz_capi==1.0.5"
]
build-backend = "backend"
backend-path = ["_custom_build"]
