name: Build

on: [push, pull_request]

jobs:
  test_cpp:
    name: test C++ sources
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: linting
      run: |
        clang-tidy *.cpp -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-cplusplus-*,clang-analyzer-*,cppcoreguidelines-*
        cppcheck --enable=all --std=c++17 --language=c++


  build_tarball:
    name: create a tarball of RapidFuzz for pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: create tarball
      run: python3 setup.py sdist

    - name: upload tarball
      uses: actions/upload-artifact@v1
      with:
        name: tarball
        path: ./dist

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    env:
      CIBW_SKIP: cp27-* pp*
      CIBW_BEFORE_BUILD: "pip install pybind11"
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse

  deploy-wheels:
    needs: [build_tarball, build_wheels]
    name: deploy wheels to pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: wheels
        path: dist

    - uses: actions/download-artifact@v1
      with:
        name: tarball
        path: dist

    - run: ls dist
