name: Build

on: [push, pull_request]

jobs:
  test_python:
    name: run linting, tests and benchmarks for the python module
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel pybind11

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build_tarball:
    needs: [test_python]
    name: create a tarball of RapidFuzz for pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: create tarball
      run: python3 setup.py sdist

    - name: upload tarball
      uses: actions/upload-artifact@v1
      with:
        name: tarball
        path: ./dist

  build_wheels:
    needs: [test_python]
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    env:
      CIBW_SKIP: cp27-* pp*
      CIBW_BEFORE_BUILD: "pip install pybind11"
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse

  deploy-wheels:
    if: github.ref == 'ref/head/master'
    needs: [build_tarball, build_wheels]
    name: deploy wheels to pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: wheels
        path: dist

    - uses: actions/download-artifact@v1
      with:
        name: tarball
        path: dist

    - run: ls dist
