name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_legacy:
    name: Build wheel for legacy Python versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CIBW_BUILD: cp27-* cp35-* pp27-*
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
